Models/Category.cs
public class Category
{
    public int CategoryId { get; set; }
    public string CategoryName { get; set; }
    public string Description { get; set; }
    public ICollection<Product> Products { get; set; }
 }

Models/Customer.cs
using System.ComponentModel.DataAnnotations;

public class Customer {
    public int CustomerId { get; set; }

    [Required(ErrorMessage = "Company name is required")]
    public string CompanyName { get; set; }
    public string Address { get; set; }
    public string City { get; set; }
    public string Region { get; set; }
    public string PostalCode { get; set; }
    public string Country { get; set; }
    public string Phone { get; set; }
    public string Fax { get; set; }
}

Models/DataContext.cs
using Microsoft.EntityFrameworkCore;

public class DataContext : DbContext
{
  public DataContext(DbContextOptions<DataContext> options) : base(options) { }

  public DbSet<Product> Products { get; set; }
  public DbSet<Category> Categories { get; set; }
  public DbSet<Discount> Discounts { get; set; }
}

Models/Discount.cs
using System.ComponentModel.DataAnnotations.Schema;
public class Discount
{
  public int DiscountId { get; set; }
  public int Code { get; set; }
  public DateTime StartTime { get; set; }
  public DateTime EndTime { get; set; }
  public int ProductId { get; set; }
  [Column(TypeName = "decimal(4,4)")]
  public decimal DiscountPercent { get; set; }
  public string Title { get; set; }
  public string Description { get; set; }

  public Product Product { get; set; }
}

Models/Product.cs
using System.ComponentModel.DataAnnotations.Schema;

public class Product
{
    public int ProductId { get; set; }
    public string ProductName { get; set; }
    public string QuantityPerUnit { get; set; }
    [Column(TypeName = "decimal(18,4)")]
    public decimal UnitPrice { get; set; }
    public short UnitsInStock { get; set; }
    public short UnitsOnOrder { get; set; }
    public short ReorderLevel { get; set; }
    public bool Discontinued { get; set; }
    public int CategoryId { get; set; }
    public Category Category { get; set; }
}

Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;

public class CustomerController : Controller
{
  // this controller depends on the NorthwindRepository
  private DataContext _dataContext;
  public CustomerController(DataContext db) => _dataContext = db;
  public IActionResult Register() => View();

  [HttpPost]
  public IActionResult Registered(Customer newCustomer) {
    if (!_dataContext.Customers.Any(c => c.CompanyName == newCustomer.CompanyName)){
      _dataContext.Add( new Customer() {
        CompanyName = newCustomer.CompanyName,
        Address = newCustomer.Address,
        City = newCustomer.City,
        Region = newCustomer.Region,
        PostalCode = newCustomer.PostalCode,
        Country = newCustomer.Country,
        Phone = newCustomer.Phone,
        Fax = newCustomer.Fax
      });

      _dataContext.SaveChanges();
    }

    return View(_dataContext.Customers.OrderBy(c => c.CompanyName));
  }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

public class HomeController : Controller
{
    // this controller depends on the NorthwindRepository
    private DataContext _dataContext;
    public HomeController(DataContext db) => _dataContext = db;
    public IActionResult Index() => View(_dataContext.Discounts.Where(d => d.StartTime <= DateTime.Now && d.EndTime > DateTime.Now).Take(3));
}

Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;

public class ProductController : Controller
{
  // this controller depends on the NorthwindRepository
  private DataContext _dataContext;
  public ProductController(DataContext db) => _dataContext = db;
  public IActionResult Category() => View(_dataContext.Categories.OrderBy(c => c.CategoryName));
  public IActionResult Discount() => View(_dataContext.Discounts.Where(d => d.StartTime <= DateTime.Now && d.EndTime > DateTime.Now).OrderBy(d => d.Title));
  public IActionResult Index(int id) => View(_dataContext.Products.Where(p => p.CategoryId == id && p.Discontinued == false).OrderBy(p => p.ProductName));
}

Views/Customer/Register.cshtml
@model Customer

<h3 class="mt-3">Register a Customer</h3>
<form asp-action="Registered">
    <div class="mb-3">
        <label asp-for="CompanyName" class="form-label">Company Name</label>
        <input asp-for="CompanyName" type="text" class="form-control">
    </div>

    <div class="mb-3">
        <label asp-for="Address" class="form-label">Address</label>
        <input asp-for="Address" type="text" class="form-control">
    </div>

    <div class="mb-3">
        <label asp-for="City" class="form-label">City</label>
        <input asp-for="City" type="text" class="form-control">
    </div>

    <div class="mb-3">
        <label asp-for="Region" class="form-label">Region</label>
        <input asp-for="Region" type="text" class="form-control">
    </div>

    <div class="mb-3">
        <label asp-for="PostalCode" class="form-label">Postal Code</label>
        <input asp-for="PostalCode" type="text" class="form-control">
    </div>

    <div class="mb-3">
        <label asp-for="Country" class="form-label">Country</label>
        <input asp-for="Country" type="text" class="form-control">
    </div>

    <div class="mb-3">
        <label asp-for="Phone" class="form-label">Phone</label>
        <input asp-for="Phone" type="text" class="form-control">
    </div>

    <div class="mb-3">
        <label asp-for="Fax" class="form-label">Fax</label>
        <input asp-for="Fax" type="text" class="form-control">
    </div>

    <button type="submit" class="btn btn-primary">Add Customer</button>
</form>

Views/Customer/Registered.cshtml
@model IEnumerable<Customer>

<h2 class="mt-3"><i class="fas fa-list-ul"></i> Customers</h2>
<div class="list-group">
    @foreach (Customer c in Model)
    {
        <a class="list-group-item list-group-item-action">@c.CustomerId - <i style="opacity:.6;">@c.CompanyName - @c.Address, @c.City, @c.Region @c.PostalCode, @c.Country - @c.Phone - @c.Fax</i></a>
    }
</div>

Views/Home/index.cshtml
@model IEnumerable<Discount>
<div class="jumbotron my-2 border border-secondary">
    <h1 class="display-4">Northwind</h1>
    <p class="lead">We have the best prices and selection of high quality foods &amp; beverages on the planet! Check out our featured discounts below.</p>
    <hr class="my-4">
    <p>For exceptional international quisuine, look no further.</p>
    <a class="btn btn-outline-primary btn-lg" href="#" role="button">Order Now</a>
</div>

<div class="row row-cols-1 row-cols-lg-3">
    @foreach (Discount d in Model)
    {
        <div class="col discounts px-2 py-4">
            <h3>@d.Title</h3>
            <div class="mb-4">
                @d.Description
            </div>
            <i>Discount expires: @d.EndTime.ToString("MM/dd/yyyy")</i><br />
            <a class="discountToastButton" data-code="@d.Code" data-product="@d.Title" data-discount="@d.DiscountPercent"><i class="far fa-hand-point-right"></i> Discount Code</a>
        </div>
    }
</div>

<div id="discountToast" class="toast">
        <div class="toast-header">
            <strong class="mr-auto" id="product"></strong>
            <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="toast-body">
            Discount: <strong id="discountPercent"></strong>%<br>
            Discount Code: <strong id="code"></strong>
        </div>
    </div>

@section Scripts {
    <script type="text/javascript" src="~/js/client.js"></script>
}

Views/Product/Category.cshtml
@model IEnumerable<Category>

<h2 class="mt-3"><i class="fas fa-list-ul"></i> Product Categories</h2>
<div class="list-group">
    @foreach (Category c in Model)
    {
        <a asp-action="Index" asp-route-id="@c.CategoryId" class="list-group-item list-group-item-action">@c.CategoryName - <i style="opacity:.6;">@c.Description</i></a>
    }
</div>

Views/Product/Discount.cshtml
@model IEnumerable<Discount>

<h2 class="mt-3"><i class="fas fa-list-ul"></i> Current Discounts</h2>
<div class="list-group">
    @foreach (Discount d in Model)
    {
        <div class="list-group-item list-group-item-action">@d.Title - Code: @d.Code - <i style="opacity:.6;">@d.Description</i></div>
    }
</div>

Views/Product/Index.cshtml
@model IEnumerable<Product>

<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Product</th>
      <th scope="col" class="text-right">Price</th>
      <th scope="col" class="text-right">Stock</th>
    </tr>
</thead>
<tbody>
  @foreach (Product p in Model)
  {
    <tr>
      <td>@p.ProductName</td>
      <td class="text-right">@string.Format("{0:c}", p.UnitPrice)</td>
      <td class="text-right">@p.UnitsInStock</td>
    </tr>
  }
  </tbody>
</table>

Views/Shared/_layout.cshtml
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <!-- bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <!-- font awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- google font -->
    <link href="https://fonts.googleapis.com/css?family=Fjalla+One" rel="stylesheet">
    <!-- client -->
    <link rel="stylesheet" href="~/css/client.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><i class="far fa-compass"></i> Northwind</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-database"></i> Products
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-controller="Product" asp-action="Category"><i class="fas fa-list-ul"></i> Browse Categories</a>
                                <a class="dropdown-item" href="#"><i class="fas fa-search"></i> Product Search</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" asp-controller="Product" asp-action="Discount"><i class="fas fa-tag"></i> Current Discounts</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Customer" asp-action="Register"><i class="fas fa-users"></i> Customers</a>
                        </li>
                    </ul>
                </div>
                <form class="form-inline my-2 my-lg-0 d-none d-md-inline">
                    <input class="form-control mr-sm-2" type="search" placeholder="Product Search" aria-label="Search">
                    <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit"><i class="fas fa-search"></i><span class="sr-only">Search</span></button>
                </form>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Northwind
        </div>
    </footer>
    <!-- jquery -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <!-- bootstrap js -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
    
    @RenderSection("Scripts", required: false)
</body>
</html>